name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Describe the problem briefly
      placeholder: App crashes when clicking save
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce it?
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
