name: "Feature Request"
description: Propose a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Who is affected?
      placeholder: Describe the current limitation or pain point.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe the desired behavior or feature.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?
      placeholder: Describe alternative solutions or workarounds.
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the expected benefit or business value?
      placeholder: Performance improvement, usability gain, revenue impact, etc.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Mockups, screenshots, links, references.
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
